binance_spot:
  market_type: spot
  fee: 0.001
  depth: 10
binance_futures:
  market_type: perp
  fee: 0.0005
  depth: 10
okx_spot:
  market_type: spot
  fee: 0.001
  depth: 5
okx_futures:
  market_type: perp
  fee: 0.0005
  depth: 5
bybit_spot:
  market_type: spot
  fee: 0.001
  depth: 5
bybit_futures:
  market_type: perp
  fee: 0.0005
  depth: 5
deribit_futures:
  market_type: perp
  fee: 0.0005
  depth: 5
