global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: api
    static_configs:
      - targets: ["api:8000"]
  - job_name: status
    static_configs:
      - targets: ["status:8001"]
