maker_fee_bps: 7.5
passive_rebate_bps: 0.0
exchanges:
  binance_api_key: ""
  binance_api_secret: ""

strategies:
  default: breakout_atr
  params:
    breakout_atr:
      offset_frac: 0.02  # Fracción base del ATR usada para cruzar el último precio con órdenes límite
    mean_rev_ofi:
      ofi_window: 20
      zscore_threshold: 1.0
      vol_window: 20
      vol_threshold: 0.8

backtest:
  data: data/examples/btcusdt_3m.csv
  symbol: BTC/USDT
  strategy: breakout_atr
  latency: 1
  window: 120
  min_fill_qty: 0.0

storage:
  backend: sqlite
  url: "sqlite:///:memory:"
balance:
  enabled: false
  threshold: 0.0
  interval: 60.0
  assets: []

router_fee_update_interval_sec: 3600.0

execution:
  limit_offset_ticks: 1.0
  limit_expiry_sec: 1.0
  requote_attempts: 5

ingestion:
  funding:
    binance_futures:
      BTC/USDT: 60
  open_interest:
    binance_futures:
      BTC/USDT: 60

risk:
  risk_pct: 0.02
  max_symbol_exposure: null
  total_cap_pct: null
  per_symbol_cap_pct: null

exchange_configs:
  binance_spot:
    market_type: spot
    maker_fee_bps: 7.5
    taker_fee_bps: 7.5
    tick_size: 0.01
    min_fill_qty: 0.0
  binance_futures:
    market_type: perp
    maker_fee_bps: 2.0
    taker_fee_bps: 4.0
    tick_size: 0.01
    min_fill_qty: 0.0
  okx_spot:
    market_type: spot
    maker_fee_bps: 8.0
    taker_fee_bps: 10.0
    tick_size: 0.1
  okx_spot_testnet:
    market_type: spot
    maker_fee_bps: 7.5
    taker_fee_bps: 7.5
    tick_size: 0.1
    min_fill_qty: 0.0
