exchanges:
  binance_api_key: ""
  binance_api_secret: ""

strategies:
  default: breakout_atr
  params:
    mean_rev_ofi:
      ofi_window: 20
      zscore_threshold: 1.0
      vol_window: 20
      vol_threshold: 0.01

backtest:
  data: data/examples/btcusdt_1m.csv
  symbol: BTC/USDT
  strategy: breakout_atr
  latency: 1
  window: 120

storage:
  backend: sqlite
  url: "sqlite:///:memory:"
balance:
  enabled: false
  threshold: 0.0
  interval: 60.0
  assets: []

ingestion:
  funding:
    binance_futures:
      BTC/USDT: 60
  open_interest:
    binance_futures:
      BTC/USDT: 60

risk:
  risk_pct: 0.02
  vol_target: 0.01
  total_cap_pct: null
  per_symbol_cap_pct: null
