apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: postgres
    secureJsonData:
      password: postgres
    database: trading
    isDefault: false
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
