name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: flake8 . --select=E9,F63,F7 --show-source --statistics
      - name: Run unit tests
        run: pytest --cov=src --cov-report=xml -m "not integration"
      - name: Run integration tests
        run: pytest tests -m integration
